// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxUGVJulGsVRyNj1rsX0IATGYee6V27mg',
    appId: '1:1071403757401:web:8fb966b72f88a2dc8ca648',
    messagingSenderId: '1071403757401',
    projectId: 'tripbudgeter-7c401',
    authDomain: 'tripbudgeter-7c401.firebaseapp.com',
    storageBucket: 'tripbudgeter-7c401.firebasestorage.app',
    measurementId: 'G-501GY0DRJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kGMCWGt_UA9ojjcqgy6XtBswe8GSDcA',
    appId: '1:1071403757401:android:86f8a175ccd446588ca648',
    messagingSenderId: '1071403757401',
    projectId: 'tripbudgeter-7c401',
    storageBucket: 'tripbudgeter-7c401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgM2J3xplPSt_Pzt1gnhMEGlDWyh2APM',
    appId: '1:1071403757401:ios:b61b99f07a81bb358ca648',
    messagingSenderId: '1071403757401',
    projectId: 'tripbudgeter-7c401',
    storageBucket: 'tripbudgeter-7c401.firebasestorage.app',
    iosBundleId: 'com.example.tripbudgeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZgM2J3xplPSt_Pzt1gnhMEGlDWyh2APM',
    appId: '1:1071403757401:ios:b61b99f07a81bb358ca648',
    messagingSenderId: '1071403757401',
    projectId: 'tripbudgeter-7c401',
    storageBucket: 'tripbudgeter-7c401.firebasestorage.app',
    iosBundleId: 'com.example.tripbudgeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxUGVJulGsVRyNj1rsX0IATGYee6V27mg',
    appId: '1:1071403757401:web:a494871542336ba88ca648',
    messagingSenderId: '1071403757401',
    projectId: 'tripbudgeter-7c401',
    authDomain: 'tripbudgeter-7c401.firebaseapp.com',
    storageBucket: 'tripbudgeter-7c401.firebasestorage.app',
    measurementId: 'G-QVW64X0N6J',
  );
}
